name: Update VPN configs

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requests
        run: pip install requests

      - name: Update configs
        run: python update.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add unified.txt

          if git diff --staged --quiet; then
            echo "Изменений нет"
          else
            git commit -m "Update VPN configs"
            git push
          fi
